import '@fortawesome/fontawesome-free/js/fontawesome'
import '@fortawesome/fontawesome-free/js/solid'
import '@fortawesome/fontawesome-free/js/regular'
import '@fortawesome/fontawesome-free/js/brands'

import dom from './modules/dom'

import './styles/main.scss'
import './assets/clear.mp4'
import './assets/clouds.mp4'
import './assets/rain.mp4'
import './assets/snow.mp4'
import './assets/fog.mp4'
import './assets/thunderstorm.mp4'
import './assets/space.mp4'
import './assets/images/clear.svg'
import './assets/images/night_clear.svg'
import './assets/images/clouds.svg'
import './assets/images/night_clouds.svg'
import './assets/images/rain.svg'
import './assets/images/snow.svg'
import './assets/images/thunder.svg'
import './assets/images/uvSun.svg'
import './assets/images/sunrise.svg'
import './assets/images/sunset.svg'
import './assets/images/humidity.svg'
import './assets/images/chanceOfRain.svg'

dom.loadContent()
